---
# handlers file for ./memcached

- name: restart memcached
  service:
      name: memcached
      state: restarted

- name: reload and restart memcached
  systemd:
      daemon_reload: yes
  notify: restart memcached
