---
# tasks file for ./roles/nginx

- name: Install nginx
  yum:
      name: nginx
      state: present
      update_cache: yes

- name: Deliver main configuration file
  template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      backup: yes
  notify: restart nginx

- name: ensure conf.d dir exists
  file:
      path: /etc/nginx/conf.d
      state: directory

- name: Copy configuration file to nginx/sites-avaiable
  template: 
      src: default.conf.j2
      dest: /etc/nginx/conf.d/default.conf
      backup: yes
  notify: restart nginx

- name: Make sure nginx start with boot
  service:
      name: nginx
      state: started
      enabled: yes

