- hosts: all
  become: yes
  become_user: root

  tasks:
      - include_role:
          name: common

- hosts: loadbalancer
  become: yes
  become_user: root

  tasks:
      - include_role:
          name: nginx

- hosts: memcached_servers
  become: yes
  become_user: root

  tasks:
      - include_role:
          name: memcached

- hosts: webservers
  become: yes
  become_user: root

  tasks:
      - include_role:
          name: tomcat
