---
# tasks file for ./roles/tomcat

- name: install jdk
  yum:
      name: java-1.7.0-openjdk
      state: present
      update_cache: yes

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user:
      name: tomcat
      group: tomcat
      home: /home/tomcat
      createhome: no
  become: yes
  become_method: sudo
  become_user: root

- name: install tomcat
  yum:
      name: tomcat
      state: present
      update_cache: yes

- name: Deliver config files for tomcat
  template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      backup: yes
  loop:
      - { src: 'default.j2', dest: '/etc/tomcat/default' }
      - { src: 'server.xml.j2', dest: '/etc/tomcat/server.xml' }
      - { src: 'context.xml.j2', dest: '/etc/tomcat/context.xml' }
  notify: restart tomcat

- name: Deliver libraries support memcached
  get_url:
      url: "{{ item }}"
      dest: /usr/share/tomcat/lib/
  loop:
      - http://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager/1.8.0/memcached-session-manager-1.8.0.jar
      - http://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager-tc7/1.8.0/memcached-session-manager-tc7-1.8.0.jar
      - https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/spymemcached/spymemcached-2.10.1.jar

- name: Deploy some app
  copy:
      src: msm-sample-webapp-1.0-SNAPSHOT.war
      dest: /var/lib/tomcat/webapps/ROOT.war
      owner: tomcat
      group: tomcat

- name: Change ownership of Tomcat installation
  file:
      path: "{{ item }}"
      owner: tomcat
      group: tomcat
      state: directory
      recurse: yes
  loop:
      - /etc/tomcat/
      - /var/lib/tomcat/
      - /usr/share/tomcat/

- name: Set tomcat to start with boot
  service:
      name: tomcat
      state: started
      enabled: yes


