---
# tasks file for ./memcached
- name: Install memcached
  yum:
      name: memcached 
      state: present
      update_cache: yes

- name: Deliver configuration file
  template:
      src: memcached.conf.j2
      dest: /etc/sysconfig/memcached
      backup: yes
  notify: restart memcached

- name: Deliver init script
  template:
      src: init.sh.j2
      dest: /etc/init.d/memcached
      mode: 0755
      backup: yes
  notify: reload and restart memcached

- name: Make sure memcached started with boot
  service:
      name: memcached
      state: started
      enabled: yes
